vault:
  - path: team_sys_ops_us/secret/prod/infra8/dns
    engineVersion: 2
    secretValues:
      - envVar: AWS_ACCESS_KEY_ID
        vaultKey: AWS_ACCESS_KEY_ID
        encoded: false
      - envVar: AWS_SECRET_ACCESS_KEY
        vaultKey: AWS_SECRET_ACCESS_KEY
        encoded: false
      - envVar: PDNS_API_KEY
        vaultKey: PDNS_API_KEY
        encoded: false
      - envVar: R53_ACCESS_KEY_ID
        vaultKey: R53_ACCESS_KEY_ID
        encoded: false
      - envVar: R53_SECRET_ACCESS_KEY
        vaultKey: R53_SECRET_ACCESS_KEY
        encoded: false
      - envVar: TF_VAR_ansible_user_name
        vaultKey: ANSIBLE_USER
        encoded: false
      - envVar: TF_VAR_ansible_private_key
        vaultKey: ANSIBLE_USER_KEY
        encoded: false
      - envVar: TF_VAR_ansible_vault_pass
        vaultKey: ANSIBLE_VAULT_PW
        encoded: false
        